Feature/25882590: grpc clients
go-park-mail-ru/2023_2_Vkladyshi pull request #19
Opened 2023-11-29 18:00 UTC by kingjoram

https://aleksejy60.kaiten.ru/space/221617/card/25882590

2023-12-09 17:31 UTC, migregal commented on cmd/authorization/main.go
>  	api.ListenAndServe()
Тут нужно делать немного иначе:

```go

	api := delivery_auth.GetApi(core, lg)

	errs := make(chan error, 2)

	go func() {
		errs <- api.ListenAndServe()
	}
	go func() {
		errs <- delivery_auth_grpc.ListenAndServeGrpc(lg)
	}
	
	err := <-errs
	// проверка ошибки и т.д.
```

Так ты можешь быть уверен в том, что обе апишки завелись и работают без ошибок

2023-12-09 17:32 UTC, migregal commented on cmd/authorization/main.go
> +	go delivery_auth_grpc.ListenAndServeGrpc(lg)
А нельзя тут сделать стандартный интерфейс?

Т.е. чтобы был ListenAndServe, а lg передавать в конструктор

2023-12-09 17:35 UTC, migregal commented on films/delivery/api.go
> +	}
Вот эту логику бы унести ввиде middleware

Пока выглядит, что в каждой функции происходит копипаста првоерки авторизации - такое тяжело проверятьь и, тем более, поддерживать

2023-12-09 17:38 UTC, migregal commented on cov.txt
Честно - так и не понял, как вы предполагаете его использовать

Этот файл то появляется, то исчезает из репы и mr'ов

Может, пора настроить .gitignore уже?)

2023-12-09 17:39 UTC, migregal commented on cmd/authorization/main.go
> +	select {}
?

2023-12-09 17:40 UTC, migregal commented on authorization/repository/profile/repo_user.go
> +	return userID, nil
Какой-то странный дифф

Это gofmt выдал?

2023-12-09 17:41 UTC, migregal commented on authorization/delivery/grpc/server.go
> +        userRepo: users,
Форматирование поехало

2023-12-09 17:42 UTC, migregal commented on authorization/delivery/grpc/server.go
> +	}, nil
Прогони-ка gofmt по всему проекту

Кажется, у кого-то из команды сломана автоматическое форматирование на сохранении

2023-12-09 17:43 UTC, migregal commented on comments/usecase/core.go
> +	conn, err := grpc.Dial(":50051", grpc.WithTransportCredentials(insecure.NewCredentials()))
Адрес под конфиг вынести бы

2023-12-09 17:43 UTC, migregal commented on comments/usecase/core.go
> +	return uint64(response.Value), nil
А почему бы в ответе сразу uint64 не отдавать? Зачем тут это приведение типа?

2023-12-09 17:45 UTC, migregal commented on films/usecase/core.go
> +	result := &requests.CalendarResponse{}
Зачем?

2023-12-09 17:49 UTC, migregal commented on films/usecase/core.go
> +	auth "github.com/go-park-mail-ru/2023_2_Vkladyshi/authorization/proto"
Чет не вижу, где этот клиент

Давай обернем в отедельную структуру и будем как и остальные зависимости пробрасывать сюда

Бенефиты:
* сохранение grpc сокединения (не нужно переустанавливать каждый раз - это значительно снижает время запроса)
* возможность написания unit тестов на core - сейчас тееб нужен отдельный grpc сервер, чтобы прогнать функции

Собственно, так как grpc соединение умеет самовосстанавливаться, смысла каждый раз дергать Dial и гонять по сети лишнюю нагрузку просто никакой

2023-12-09 17:49 UTC, migregal approved these changes
Оставил замечания

2023-12-10 17:39 UTC, migregal commented on authorization/usecase/core.go
> +var LostConnection = errors.New("Redis connection lost")
В гошке принято давать префик Err переменным-ошибкам, чтобы отличать их от остальных

```suggestion
var ErrInvalideEmail = errors.New("invalide email")
var ErrLostConnection = errors.New("Redis connection lost")
```

2023-12-10 17:42 UTC, migregal commented on comments/usecase/core.go
> +	return uint64(response.Value), nil
У тебя ж тут значение уже типа uint64 - зачем лишний раз тип приводить?

2023-12-10 17:43 UTC, migregal commented on films/usecase/core.go
> +	return uint64(response.Value), nil
У тебя ж тут значение уже типа uint64 - зачем лишний раз тип приводить?

2023-12-10 17:45 UTC, migregal commented on pkg/middleware/grpc_client.go
> +}
Это не middleware))

Хороший пример middleware на go описан вот тут https://www.alexedwards.net/blog/making-and-using-middleware

В целом вся идея middleware в том, что он оборачивает вашу API доп слоем, чтобы переиспользовать одну и ту же логику без копипасты

В данном случае - проверка авторизации клиента

2023-12-10 17:45 UTC, migregal requested changes
Есть еще что поправить

2023-12-18 08:45 UTC, migregal commented on middleware/middleware.go
> +		requests.SendResponse(w, *mw.Response, lg)
Вот это тут зачем?

В случае успешной проверки авторизации клиенту ответит next, а не middleware

2023-12-18 08:49 UTC, migregal commented on middleware/middleware.go
> +		mw.Metrix.Time.WithLabelValues(strconv.Itoa(mw.Response.Status), r.URL.Path).Observe(end.Seconds())
Вот это не понял

Разве тут не будет всегда 200 писаться?

2023-12-18 08:50 UTC, migregal commented on middleware/middleware.go
> +		mw.Metrix.Time.WithLabelValues(strconv.Itoa(mw.Response.Status), r.URL.Path).Observe(end.Seconds())
Смысл этой метрики в auth middleware ?

Кажется, что они должны быть в middleware на уровень выше, в статистике

Туда ваш soft статус можно пробросить через context, опять же

2023-12-18 08:54 UTC, migregal commented on comments/delivery/api.go
> +		a.mw.Response.Status = http.StatusBadRequest
Вся идея middleware в том, что функции "под" ним не зеают о его существовании

Зачем завязываться на наличие mw здесь? Если захотим использовать другой middleware, придется все переписывать, а не просто функцию поменять в api.go

2023-12-18 08:55 UTC, migregal requested changes
По middleware поглядел, оставил замечания

2023-12-19 19:04 UTC, migregal commented on pkg/requests/responses.go
> +		sendMetrics(mt, path, http.StatusInternalServerError, start)
Это как?


Т.е. если у меня 200-ка, но сервер не смог собрать json'ку, по на метриках будет 2 хита вместо 1?

Кажется, что sendMetrics с response.Status должна быть после проверки ошибки

2023-12-19 19:57 UTC, migregal commented on middleware/middleware.go
> +func AuthCheck(next http.Handler, core *usecase.Core, lg *slog.Logger) http.Handler {
Ткни пальцем, пожалуйста, где он используется - не вижу в mr'е, слишком большой

2023-12-19 19:59 UTC, migregal commented on comments/delivery/api.go
>  	userId, err := a.core.GetUserId(r.Context(), session.Value)
Вот тут не понял, честно говоря

У нас же для этого служит middleware, нет?

2023-12-19 20:02 UTC, JuFnd commented on middleware/middleware.go
> +func AuthCheck(next http.Handler, core *usecase.Core, lg *slog.Logger) http.Handler {
films/delivery/api.go - func GetApi(....) { .... }

2023-12-19 20:05 UTC, migregal commented on pkg/requests/responses.go
> +func SendResponse(w http.ResponseWriter, path string, response Response, lg *slog.Logger, mt *metrics.Metrics, start time.Time) {
Давай, тогда уж, сделаем структуру, в которой будет единственное поле `mt` и единстенный метод `SendResponse`

А то каждый раз пробрасывать mt сюда выглядит больно

2023-12-19 20:09 UTC, migregal commented on authorization/delivery/http/api.go
> +		requests.SendResponse(w, r.URL.Path, response, a.lg, a.mt, start)
Давайте в SendResponse прокидывать пару

```
w http.ResponseWriter, r *http.Request
```

а не `w` и `path` - тогда в лог в SendResponse можно со временем добавлять заголовки, доп параметры какие-нибудь вытягивать и т.д.

А сейчас выглядит как костыль с кучей копипасты: "Не забудь вот тут передать вот это, затем вызвать это, потом вот то и уже в конце прокинь вот то поле, которое ....
"

2023-12-19 20:10 UTC, migregal requested changes
Пара вопросов + не вижу, где бы применился новый middleware + тесты красные

2023-12-19 20:11 UTC, migregal commented on usecase/core.go
А у нас что-то осталось в общих usecase/delivery/repository ? Надо бы доразнести это, чтобы остались только явно выделенные микросервисы

2023-12-19 20:15 UTC, JuFnd commented on usecase/core.go
ничего не осталось

2023-12-20 08:25 UTC, migregal commented on cmd/films/films
Бинарь из репы надо удалить

2023-12-20 08:26 UTC, migregal commented on cmd/films/films_log.log
Это тоже долой

2023-12-20 08:33 UTC, migregal commented on configs/config.go
> +	Calendar_db   string `yaml:"calendar_db"`
У вас linter на такие названия не ругается, разве?

Чет только сейчас заметил. В golang ж только CamelCase используется, никаких подчеркиваний в названиях полей/переменных

2023-12-20 08:33 UTC, migregal commented on configs/config.go
> +	Calendar_db   string `yaml:"calendar_db"`
Линтер включен, вообще?)

2023-12-20 09:21 UTC, migregal approved these changes
lgtm

2023-12-20 09:21 UTC, merged