Feature/21151804
go-park-mail-ru/2023_2_Vkladyshi pull request #2
Opened 2023-09-30 21:07 UTC by kingjoram

Подборка фильмов для дз0 (с заглушкой на бд)
карточка https://aleksejy60.kaiten.ru/space/221617/card/21151804

2023-09-30 21:19 UTC, JuFnd commented on api.go
> +		a.core.lg.Debug(err.Error(), "can't find page")
Кажется тут нужен return?

2023-09-30 22:29 UTC, migregal commented on LICENSE
> -MIT License
А зачем чистить файлы?

Какие-то требования появились?

2023-09-30 22:30 UTC, migregal commented on README.md
> -Backend репозиторий команды Вкладыши
Тут тоже вопрос - будто бы не влимяет на твою фичу

2023-09-30 22:32 UTC, migregal commented on api.go
> +	Status int
Вы с фронтом договорились на внутренний статус?

Для http можно использовать два варианта:

*  Через Header установить статус, например так:
```go
w.WriteHeader(http.StatusInternalServerError)
```
* Отправлять только ошибки, т.к. 200-ый статус улетает по-умолчанию (текст сообщения можно менятть, ествесственно)
```go
    http.Error(w, http.StatusText(http.StatusNotFound), http.StatusNotFound)
```

2023-09-30 22:33 UTC, migregal commented on api.go
> +	Page   uint64 `json:"current_page"`
Еще бы page_size сюда, раз сразу с пагинацией решили делать

2023-09-30 22:34 UTC, migregal commented on api.go
> +	page, err := strconv.ParseUint(r.URL.Query().Get("page"), 10, 64)
И тут принимать page_size, чтобы фронт мог отрисовывать формочки как им нужно

2023-09-30 22:34 UTC, migregal commented on api.go
> +	w.Header().Set("Content-Type", "application/json")
Я бы в самом конце выставлял, прям перед w.Write

2023-09-30 22:35 UTC, migregal commented on api.go
> +		a.core.lg.Debug(err.Error(), "can't find page")
Обычно page и page_size - опциональные параметры, т.е. если их не указывать, прилетит либо все (что не очень хорошо), либо условная 1ая страница с размером, скажем, 25 записей на страницу

2023-10-01 19:22 UTC, migregal commented on api.go
> +	rating   float64
У тебя поля не экспортируемые - поэтому их не будет в ответе

Нужно вот так
```suggestion
	Title    string
	ImageURL string `json:"imagine_url"`
	Rating   float64
```

2023-10-01 19:23 UTC, migregal commented on api.go
> +	core *Core
У API должен быть свой lg *slog.Logger - мы к след РК унесем Core в отдельный модуль и его логгер перестанет быть доступным

2023-10-01 19:23 UTC, migregal commented on api.go
> +	response := FilmsResponse{
Синканитесь, как обсуждали

Мб, стоит дождаться мержа второго pr'а

2023-10-01 19:23 UTC, migregal requested changes
Оставил замечания

2023-10-02 12:20 UTC, migregal commented on api.go
> +func (a *API) Films(w http.ResponseWriter, r *http.Request) {
Давй еще проверим, что тут method == GET, потому что через эту же апишку, по идее, но с уже с POST будем добавлять фильмы, потом

2023-10-02 12:23 UTC, migregal commented on main.go
> +	api := API{core: &core, lg: slog.New(slog.NewJSONHandler(apiLogFile, nil))}
Обычно делают так

```suggestion
	logFile, _ := os.Create("log.log")

	lg := slog.New(slog.NewJSONHandler(logFile, nil))

	core := Core{lg: lg.With("module", "core")}
	api := API{core: &core, lg: lg.With("module", "api")}
```

Тогда у вас один файл ==> его проще обслуживать. + Есть вся хронология событий с разделением по модулям

2023-10-02 12:25 UTC, migregal commented on api.go
> +		response.Body = nil
Это уже лишнее, ты же их все равно не отдаешь

Если ломается что-то настолько глобальное, как стандартная бибилиотека, можно спокойно кидать InternalServerError - у вас в коде точно что-то не так, тогда

2023-10-02 12:26 UTC, migregal commented on api.go
> +		response.Body = nil
Например, тут у тебя сломался json модуль

Для этого нужна либо какая-то битая память (а вы тут с unsafe вроде не работаете), либо прям ошибка уровня ОС (например, работа с ОЗУ)

2023-10-02 12:26 UTC, migregal commented on api.go
> +		response.Body = nil
Например, тут у тебя сломался json модуль

Для этого нужна либо какая-то битая память (а вы тут с unsafe вроде не работаете), либо прям ошибка уровня ОС (например, работа с ОЗУ)

2023-10-02 12:27 UTC, migregal commented on api.go
> +		response.Body = nil
+ Еще лучше бы избавляться от magic numbers в коде

2023-10-02 12:32 UTC, migregal requested changes
В целом пойдет, остались финальные правки и можно мержать

2023-10-02 19:29 UTC, migregal commented on api.go
> +		a.lg.Debug(err.Error(), "json packing err")
Тут немного напутал - надо так

```suggestion
		a.lg.Error("failed to pack json", "err", err.Error())
```

Т.е. сначала идет сообщение, которое хочешь записать, а потом ключ-значения для аргументов. Плюс еще сменим Debug на Error, чтобы явно указать, что это прям ошибка

2023-10-02 19:37 UTC, migregal commented on api.go
> +		page, _ := strconv.ParseUint(r.URL.Query().Get("page"), 10, 64)
Добавь обработку ошибок сюда еще

2023-10-02 19:38 UTC, migregal commented on api.go
> +}
Вот это бы в файл core.go унести

2023-10-02 19:38 UTC, migregal commented on api.go
> +
Не хватает go.mod еще, посмотри, как в https://github.com/go-park-mail-ru/2023_2_Vkladyshi/pull/3 сделано

2023-10-02 21:32 UTC, migregal commented on main.go
> +	api := API{core: &core, lg: lg.With("module", "api")}
Тут чет module и там и там в With прокинут)

Давай сделаем все же api и core, чтобы понятно было что откуда идет

2023-10-02 22:04 UTC, migregal commented on main.go
> +	api := API{core: &core, lg: lg.With("module", "api")}
my bad, к вечеру глаз замылился

2023-10-02 22:30 UTC, migregal approved these changes
мне ок

2023-10-02 22:31 UTC, merged