Feature/21152099
go-park-mail-ru/2023_2_Vkladyshi pull request #3
Opened 2023-10-01 15:19 UTC by JuFnd

Допилил регистрацию и авторизацию с отдачей куки. Сделал несколько шаблонов для более удобного парсинга запросов и отдачи ответов. https://aleksejy60.kaiten.ru/space/221617/card/21152099

2023-10-01 18:27 UTC, migregal commented on api.go
> +func (a *API) Films(w http.ResponseWriter, r *http.Request) {
А оно точно не в [21151804](https://github.com/go-park-mail-ru/2023_2_Vkladyshi/pull/2) дожно делаться?

2023-10-01 19:01 UTC, migregal commented on requests.go
> +}
```suggestion
type Response struct {
	Status int
	Body   any
}
```

2023-10-01 19:03 UTC, migregal commented on api.go
> +	fmt.Println(request.Login, " ", request.Password, " ", request.Email)
Либо через логгер, либо долой

2023-10-01 19:03 UTC, migregal commented on api.go
> +	json.Unmarshal(body, &request)
Обработки ошибок не хватает

2023-10-01 19:05 UTC, migregal commented on core.go
> +	http.SetCookie(*w, cookie)
Это уносим в руки апишки, т.к. core не обязательно знать, что сервис работает по http

Например, в следующих РК мы уже будем на grpc пересаживаться

2023-10-01 19:11 UTC, migregal commented on core.go
>  	lg *slog.Logger
Форматтер не отработал

2023-10-01 19:11 UTC, kingjoram reviewed
ну, вроде, чет нашел

2023-10-01 19:11 UTC, kingjoram commented on api.go
> +	bytes, _ := json.Marshal(answer)
я бы все-таки как-нибудь нормально назвал, а не bytes

2023-10-01 19:11 UTC, kingjoram commented on core.go
> +var letterRunes = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
а разве нельзя как-то адекватно через byte также сделать?

2023-10-01 19:13 UTC, migregal commented on core.go
> +	Sessions map[string]string
Сюда бы структурку по типу

```go
type Session struct {
    Login string
    ExpiresAt int // вот тут уточнить, что time.Unix() возвращает
}
```

Это нужно, чтобы со стороны бека сессии так же инвалидировались

2023-10-01 19:14 UTC, migregal commented on core.go
> +	"log"
Будто бы лишнее

Примени вот это, плиз

```bash
gofmt -s -w ./
```

2023-10-01 19:16 UTC, migregal commented on main.go
> +	api.Core.Users = make(map[string]User.User)
Давай чуть структурируем мешанину

```suggestion
	core := Core.Core{
	    Lg: log.New(logFile, "", log.LstdFlags),
	    Sessions: make(map[string]string),
	    Users: make(map[string]User.User)
	}

	api := Api.API{Core: &core}
```

2023-10-01 19:17 UTC, migregal commented on main.go
>  	mx := http.NewServeMux()
Его бы ближе к месту использования перенести

Я бы скалаз, что mx нужен только после создания переменной API

2023-10-01 19:18 UTC, migregal commented on api.go
> +		w.WriteHeader(http.StatusFound)
Found все-таки больше для редиректов используется

Если вы хотите явно отдавать ошибку, можно условный 409 кинуть - Conflict

2023-10-01 19:19 UTC, migregal requested changes
Пара заечаний, в целом ок

2023-10-01 19:25 UTC, migregal commented on api.go
> +	Core *Core.Core
core не нужно экспортировать, это детали реализации

Давай что-то типа такого (логгер добавил для будущих использований)

```suggestion
	core *Core.Core
	lg *slog.Logger
```

2023-10-01 19:25 UTC, migregal commented on api.go
> +	body, _ := io.ReadAll(r.Body)
Ошибки везде проверяй, плиз

2023-10-01 19:26 UTC, migregal commented on api.go
> +	json.Unmarshal(body, &request)
Вот тут тоже ошибка потерялась - будет код 400 (BadRequest)

2023-10-01 19:27 UTC, migregal commented on api.go
> +	body, _ := io.ReadAll(r.Body)
Тут можно как 400, так и 500 кинуть, зависит от ошибки

2023-10-01 20:47 UTC, migregal commented on api.go
> +	bytes, _ := json.Marshal(answer)
Угу, переименовать бы, чтобы с пакетом не пересекалось по названию

2023-10-02 12:03 UTC, migregal commented on api.go
> +	if err != nil {
Давай для краткости так записывать

```suggestion
	if err = json.Unmarshal(body, &request); err != nil {
```

В сотальных местах тоже, плиз

2023-10-02 12:04 UTC, migregal commented on api.go
> +	if err != nil {
Вот тут лучше так. Тогда у тебя логически сгруппировано получение и обработка ошибок

```suggestion
	body, err := io.ReadAll(r.Body)
	if err != nil {
```

2023-10-02 12:07 UTC, migregal commented on main.go
> +	api := Api.API{Core: &core}
А что такое Api.API ?

Позапускай код локально, чтобы оно компилировалось и запускалось, плиз

2023-10-02 12:08 UTC, migregal commented on api.go
> +		w.WriteHeader(http.StatusConflict)
Тут уже InternalServerError, а не Conflict - мы же смогли все создать, но ошибим на формировании json'ки

2023-10-02 12:09 UTC, migregal commented on api.go
> +		w.WriteHeader(http.StatusConflict)
Тут тоже InternalServerError, а не Conflict

Напомни, плиз, на след созвоне подетальнее про http коды поговорить

2023-10-02 12:09 UTC, migregal requested changes
В целом ок, осталась пара мелких замечаний - смотри незакрытые треды

2023-10-02 12:11 UTC, migregal commented on core.go
> +var letterRunes = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
В этом кейсе все норм - можно и так и так, особой разницы не будет

2023-10-02 18:48 UTC, kingjoram reviewed
аккуратнее с resolve, а то забываешь иногда исправлять)

2023-10-02 18:48 UTC, kingjoram commented on api.go
> +		w.WriteHeader(http.StatusUnauthorized)
ну, если мы решили везде, где возможно, делать через response, то надо такое переделать. мб обернуть во что-то и через break выходить к отправке?

2023-10-02 18:48 UTC, kingjoram commented on api.go
> +	bytes, err := json.Marshal(response)
все еще не переименовал

2023-10-02 18:48 UTC, kingjoram commented on api.go
> +		w.WriteHeader(http.StatusMethodNotAllowed)
про это я спросил, ждем ответа в тг от ментора

2023-10-02 18:48 UTC, kingjoram commented on core.go
> -	lg *slog.Logger
а зачем логгер убрал?

2023-10-02 18:48 UTC, kingjoram commented on api.go
> +	bytes, err := json.Marshal(response)
бутес =)

2023-10-02 19:19 UTC, migregal commented on api.go
> +	delete(a.core.Sessions, session.Value)
Вот это уносим в метод core - нельзя обращаться к данным другого "слоя" логики напрямую, только через обертку

2023-10-02 19:20 UTC, migregal commented on api.go
> +	a.core.Mutex.Unlock()
Вот это тоже в метод core уносим

2023-10-02 19:21 UTC, migregal commented on api.go
> +	a.core.Mutex.Unlock()
И вот это тоже в метод, плиз

2023-10-02 19:23 UTC, migregal commented on api.go
> +	a.core.Mutex.RUnlock()
И вот это в метод core уносим

2023-10-02 19:30 UTC, migregal commented on go.mod
> +module github.com/go-park-mail-ru/2023_2_Vkladyshi/
Тут лишнее

```suggestion
module github.com/go-park-mail-ru/2023_2_Vkladyshi
```

2023-10-02 19:31 UTC, migregal commented on api.go
> +	Lg   *slog.Logger
Логгер тоже не экспортируемый должен быть

```suggestion
	lg   *slog.Logger
```

2023-10-02 21:04 UTC, JuFnd commented on core.go
> -	lg *slog.Logger
уносим в апишку

2023-10-02 21:30 UTC, migregal approved these changes
мне ок

2023-10-02 21:31 UTC, merged