Feature/21605710: исправление замечаний после рк
go-park-mail-ru/2023_2_Vkladyshi pull request #8
Opened 2023-10-04 17:54 UTC by kingjoram

https://aleksejy60.kaiten.ru/space/221617/card/21605710

2023-10-06 15:28 UTC, migregal commented on api.go
> +	if uint64(cap(films)) < page*pageSize {
Лучше на len, а не cap смотреть

2023-10-06 15:29 UTC, migregal requested changes
Небольшое исправление и го мержать

2023-10-07 01:52 UTC, kingjoram commented
там еще нужна валидация емейла/пароля

2023-10-11 13:24 UTC, migregal approved these changes
lgtm

2023-10-11 13:26 UTC, migregal requested changes
Порезолвьте конфликты с мастером и давайте мержать, раз закончили

2023-10-13 23:45 UTC, migregal approved these changes
lgtm

2023-10-13 23:46 UTC, merged